name: Bug Report
about: Report a problem
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: "Thanks for helping us improve CatNoteInput."
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A short description of the bug.
      placeholder: "The app shows HTTP 404 when..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What did you do?
      placeholder: "1. ...\n2. ...\n3. ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App Version
      placeholder: "0.1.0"
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "Windows 11"
