name: Feature Request
about: Suggest an idea
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: "Thanks for your idea!"
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A short description of the feature.
      placeholder: "Add bulk import"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this needed?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
